version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: payload-next-app:latest
    container_name: payload-next-app
    env_file:
      - .env
      - test.env
    ports:
      - "${PORT}:3000"
    depends_on:
      - postgres
    restart: unless-stopped
    command: ["npm", "run", "dev"]
    volumes:
      - ./media:/app/media

  postgres:
    image: docker.io/library/postgres:16
    container_name: payload-postgres
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
      POSTGRES_DB: payload
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
