import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{ts,tsx,js,jsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#444654',
        'on-tertiary-container': '#ffc0aa',
        'surface-container-low': '#f3f4f5',
        'primary-container': '#2e47d1',
        background: '#f8f9fa',
        'tertiary-fixed': '#ffdbce',
        'on-primary-fixed-variant': '#1432c0',
        'surface-tint': '#364ed8',
        'on-secondary-container': '#586579',
        'surface-dim': '#d9dadb',
        'on-tertiary-fixed-variant': '#802a00',
        'secondary-fixed': '#d6e3fb',
        'surface-bright': '#f8f9fa',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#3b485a',
        'primary-fixed': '#dee0ff',
        'surface-variant': '#e1e3e4',
        'inverse-primary': '#bbc3ff',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#000f5d',
        'inverse-on-surface': '#f0f1f2',
        'secondary-container': '#d6e3fb',
        'on-error': '#ffffff',
        'tertiary-container': '#9d3500',
        'on-surface': '#191c1d',
        'surface-container-lowest': '#ffffff',
        'tertiary-fixed-dim': '#ffb59a',
        'secondary-fixed-dim': '#bac7de',
        secondary: '#525f73',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'outline-variant': '#c5c5d7',
        outline: '#757686',
        'surface-container': '#edeeef',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#0f1c2d',
        'on-background': '#191c1d',
        primary: '#0429ba',
        'on-tertiary-fixed': '#380d00',
        tertiary: '#762600',
        'surface-container-high': '#e7e8e9',
        'primary-fixed-dim': '#bbc3ff',
        'surface-container-highest': '#e1e3e4',
        surface: '#f8f9fa',
        'inverse-surface': '#2e3132',
        'on-tertiary': '#ffffff',
        'on-primary-container': '#c5cbff',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

export default config
